irdevice  = "/dev/input/event1"
mpdhost   = "127.0.0.1:6600"
mpdpass   = ""

[Leds]
    orange  = "/sys/class/leds/orange:ph20:led1/brightness"
    green   = "/sys/class/leds/green:ph07:led4/brightness"
    blue    = "/sys/class/leds/blue:ph21:led2/brightness"
    white   = "/sys/class/leds/white:ph11:led3/brightness"

[Hotkeys]
    KEY_RO = "play"
    KEY_A  = "stop"
    KEY_F12 = "previous"
    KEY_KATAKANA = "next"
    KEY_8 = "random"
    KEY_7 = "repeat"
    KEY_KATAKANAHIRAGANA = "volume_up"
    KEY_ZENKAKUHANKAKU = "volume_down"
    KEY_6 = "keylock"
    KEY_MINUS = "playlist1"
    KEY_EQUAL = "playlist2"
    KEY_BACKSPACE = "playlist3"
    KEY_Q = "playlist4"
    KEY_W = "playlist5"
    KEY_E = "playlist6"
    KEY_T = "playlist7"
    KEY_Y = "playlist8"
    KEY_U = "playlist9"
    KEY_P = "playlist0"

[Playlists]
    playlist1 = "myplaylist1"
    playlist2 = "myplaylist2"
    playlist3 = "myplaylist3"
    playlist4 = "myplaylist4"
    playlist8 = "myplaylist8"
    playlist9 = "myplaylist9"
    playlist0 = "myplaylist0"
